language: java

script:
  - jdk_switcher use oraclejdk8
  - ./download_processing.sh
  - ./download_ketai.sh
  - ./build.sh

after_failure:
  - find . | egrep "processing-java"
  - find . | egrep "sketchbook"
  - find . | egrep "libraries"

after_success:
  - find . | egrep "processing-java"
  - find . | egrep "sketchbook"
  - find . | egrep "libraries"
